config/routes.rb
Rails.application.routes.draw do

  get 'reviews/index'

  root 'pages#index'
  get 'pages/index'

  devise_for :users, 
  	path: '', 
  	path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile'},
  	controllers: {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:show]

  resources :rooms do
    resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end
  
	resources :photos
  resources :contacts, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/trips' => 'reservations#trips'
  get '/my_reservations' => 'reservations#my_reservations'
	
  post "/trips" => "reservations#trips"
  post "/notify" => "reservations#notify"

  get '/search' => "pages#search"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :contact
  belongs_to :user

  validates_presence_of :content, :contact_id, :user_id

  def message_time
    created_at.strftime("%m월 %d일")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact

  def index
    if current_user == @contact.sender || current_user == @contact.recipient
      # 접속중인 유저가 contact.sender, recipient 둘중에 하나일 경우
      # 다른사람은 접속중인 유저가 sender일 때는 recipient, 반대일때는 sender
      @other = current_user == @contact.sender ? @contact.recipient : @contact.sender
      @messages = @contact.messages.order("created_at DESC")
    else
      # 접속중인 유저가 contact.sender, recipient가 아닐경우
      redirect_to contacts_path, alert: "권한이 없습니다."
    end
  end

  def create
    @message = @contact.messages.new(messages_params)
    @messages = @contact.messages.order("created_at DESC")

    if @message.save
      respond_to do |format|
        format.js
      end
    end
    
  end

  private
  
  def set_contact
    @contact = Contact.find(params[:contact_id])
  end

  def messages_params
    params.require(:message).permit(:content, :user_id)
  end

end

app/views/messages/_message.html.erb
  <div class="panel">
    <div class="panel-body">
      <%= image_tag avatar_url(message.user), class: "avatar-small img-circle"%> <strong><%= message.user.username%></strong>
      <span class="pull-right"><%= message.message_time%></span>
      <div class="row-space-2">
        <%= message.content%>
      </div>
    </div>
  </div>

app/views/messages/create.js.erb
<% publish_to contact_messages_path(@contact) do %>
  $("#chat").prepend("<%=j(render @message) %>");
<% end %>
  $("#new_message")[0].reset();

app/views/messages/index.html.erb
<div class="container margin-top">
  <div class="row">
    <div id="compose-message" class="panel panel-default">
      <div class="panel-heading">
        <h4>호스트에게 연락하기</h4>
      </div>
      
      <div class="panel-body panel-dark">
        <div class="col-xs-3 dark-bgc">
          <div class="text-center">
            <%=link_to @other do %>
              <%= image_tag avatar_url(@other), class: "img-circle avatar-xlarge"%>
            <%end%>
            <h4 style="overflow-wrap: break-word;"><%=@other.username%></h4>
          </div>
          <hr style="width: 48px; margin-left: 0px; height: 2px;">

          <p>
            다음 내용을 공유해주시기 바랍니다.
          </p>
          <ul class="disc">
            <li><%=@other.username%>님에게 자기 소개를 하세요</li>
            <li>여행지에 오게 된 이유는 무엇인가요? 누구와 같이 오시나요?</li>
            <li>이 숙소의 어떤 점이 마음에 드시나요? 말씀해 주세요!</li>
          </ul>
          <br>
        </div>

        <div class="col-xs-9" style="padding: 0 25px;">
          <h4 class="margin-top">언제 여행하실 계획인가요?</h4>
          
          <%=form_for [@contact, @contact.messages.new], remote: true do |f|%>
            <div class="form-group margin-top">
              <%= f.text_area :content, placeholder: "메시지 쓰기...", class: "form-control"%>
            </div>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="actions margin-top">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-medium margin-right"%>
              <%= f.submit "메시지 보내기", class: "btn btn-lg btn-green"%>
            </div>
          <%end%>

          <br>

          <div id="chat" class="well">
            <%if @messages.length > 0%>
              <%= render @messages, locals: {contact: @contact}%>
            <%else%>
              <h4>아직 메시지가 없습니다.</h4>
            <%end%>
          </div> <!-- well -->
        </div> <!-- col-xs-9 -->
      </div> <!-- panel-body -->
    </div> <!-- compose-message -->
  </div>
</div>


<%= subscribe_to contact_messages_path(@contact)%>