config/routes.rb
Rails.application.routes.draw do

  get 'reviews/index'

  root 'pages#index'
  get 'pages/index'

  devise_for :users, 
  	path: '', 
  	path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile'},
  	controllers: {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:show]

  resources :rooms do
    resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end
  
	resources :photos
  resources :contacts, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/trips' => 'reservations#trips'
  get '/my_reservations' => 'reservations#my_reservations'
	
  post "/trips" => "reservations#trips"
  post "/notify" => "reservations#notify"

  get '/search' => "pages#search"
end

app/views/share/_devise-message.html.erb
<% unless resource.errors.empty?%>
	<script>
		<%resource.errors.full_messages.each do |msg|%>
			toastr.warning('<%= msg%>')
		<%end%>
	</script>
<%end%>

app/views/share/_login-modal.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-body">
        <%=link_to user_facebook_omniauth_authorize_path, class: "btn btn-lg btn-wide btn-facebook", style: "margin-bottom: 5px;" do%>
          <i class="fa fa-facebook" aria-hidden="true"></i> 페이스북 계정으로 로그인
        <%end%>
        <%=link_to user_google_oauth2_omniauth_authorize_path, class: "btn btn-lg btn-wide btn-google" do %>
          <i class="fa fa-google" aria-hidden="true"></i> 구글 계정으로 로그인
        <%end%>
        <div class="signup-or-separator">
          <span class="h6 signup-or-separator--text">또는</span>
          <hr>
        </div>

      <!-- devise new_session -->
      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="field">
          <%= f.email_field :email, autofocus: true , placeholder: "이메일 주소", class: "form-control form-sign"%>
        </div>

        <div class="field">
          <%= f.password_field :password, autocomplete: "off" , placeholder: "비밀번호", class: "form-control form-sign"%>
        </div>
        
        <hr>

        <% if devise_mapping.rememberable? -%>
          <div class="field">
            <%= f.check_box :remember_me %>
            <%= f.label "비밀번호 저장" %>
          </div>
        <% end -%>
        
        <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
          <p><%= link_to "로그인하실 수 없나요?", new_password_path(resource_name),  class: "font-green" %><br /></p>
        <% end %>


        <div class="actions">
          <%= f.submit "로그인", class: "btn btn-lg btn-wide btn-green" %>
        </div>
        
        <hr>

        <% if devise_mapping.registerable? && controller_name != 'registrations' %>
          에어비앤비 계정이 없으세요? <%= link_to "회원가입", new_registration_path(resource_name) %><br />
        <% end -%>

      <% end %>

      </div> 
      <!-- modal-body end -->

    </div>
  </div>
</div>

app/views/share/_message.html.erb
<% unless flash.empty?%>
	<script>
		console.log('<%=flash%>');
		<%flash.each do |f|%>
			<%type = f[0].to_s.gsub('alert','warning').gsub('notice','success')%>
			toastr['<%= type%>']('<%= f[1]%>')
		<%end%>
	</script>
<%end%>

<!-- flash[:notice] = "Email is incorrect" 의 경우-->
<!-- notice가 f[0], Emails is incorrect 가 f[1] -->

app/views/share/_navbar-fixed-top.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-airbnb navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a id="toggleLogo" class="navbar-brand"><%=image_tag("logo.svg", alt: "airbnb logo")%><span id="logoArrow" class="caret"></span></a>
      <a id="notToggleLogo" href="/" class="navbar-brand"><%=image_tag("logo.svg", alt: "airbnb logo")%></a>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="mobileView"><%=link_to "홈", root_path %></li>
        <hr class="mobileView">
        <li class="mobileView"><%=link_to "호스팅하기", new_room_path %></li>

        <li class="dropdown mobileHide">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            호스트
          </a>
          <ul class="dropdown-menu">
            <li><%=link_to "숙소 등록", new_room_path %></li>
            <li><%=link_to "숙소 관리", rooms_path%></li>
          </ul>
        </li>
        
      <%if(!current_user)%>
        <li><a data-toggle="modal" data-target="#signupModal" style="cursor: pointer;">회원가입</a></li>
        <li><a data-toggle="modal" data-target="#loginModal" style="cursor: pointer;">로그인</a></li>
      <%else%>
        <li><%=link_to("메시지", contacts_path)%></li>
        <li><%=link_to("여행", trips_path)%></li>
        <hr class="mobileView">
        <li class="mobileView"><%=link_to "프로필보기", current_user %></li>
        <li class="mobileView"><%=link_to "계정관리", edit_user_registration_path%></li>
        <li class="mobileView"><%=link_to "로그아웃", destroy_user_session_path, method: :delete%></li>

        <li class="dropdown mobileHide">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%=image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
          </a>
          <ul class="dropdown-menu">
            <li><%=link_to "프로필보기", current_user %></li>
            <li><%=link_to "계정관리", edit_user_registration_path%></li>
            <li><%=link_to "로그아웃", destroy_user_session_path, method: :delete%></li>
          </ul>
        </li>
      <%end%>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<script>
  (function(){

    var logo = document.getElementById('toggleLogo');
    var Arrow = document.getElementById('logoArrow');

    function setAttributes(el, attrs) {
      for(var key in attrs) {
        el.setAttribute(key, attrs[key]);
      }
    };

    setAttributes(logo, {"data-toggle":"collapse", "data-target":"#navbar", "aria-expanded":"false", "aria-controls":"navbar"});
    logo.addEventListener('click', function(){
      Arrow.classList.toggle('rotate');
    })
  }());
  

</script>

app/views/share/_room-img-slider-modal.html.erb
<div class="modal fade" id="imgModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
       
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <%@room.photos.each do |photo|%>
            <div class="item">
              <%=image_tag photo.image.url(), class: "img-responsive"%>
            </div>
          <%end%>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>

<script>
  $('#myCarousel .item:first-child').addClass('active')
</script>

app/views/share/_signup-modal.html.erb
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-body">
        <h3>가입 절차를 시작합니다. 금방 끝나요!</h3>
        <%=link_to "패이스북", user_facebook_omniauth_authorize_path, class: "font-green"%> 또는 <%= link_to "구글", user_google_oauth2_omniauth_authorize_path, class: "font-green"%>로 회원 가입하세요.

        <div class="signup-or-separator">
          <span class="h6 signup-or-separator--text">또는</span>
          <hr>
        </div>

      <!-- devise new_session -->
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= render 'share/devise-message'%>
        <div class="field">
          <%= f.email_field :email, autofocus: true , placeholder: "이메일 주소", class: "form-control form-sign"%>
        </div>

        <div class="field">
          <%= f.text_field :username, placeholder: "이름", class: "form-control form-sign"%>
        </div>

        <div class="field">
          <%= f.password_field :password, autocomplete: "off" , placeholder: "비밀번호 설정", class: "form-control form-sign"%>
        </div>
        
        <hr>

        <div class="actions">
          <%= f.submit "회원가입" , class: "btn btn-lg btn-wide btn-green"%>
        </div>

        <hr>

        이미 에어비앤비 계정이 있나요? <%= link_to "로그인", new_user_session_path, class: "font-green" %><br />
      <% end %>

      </div> 
      <!-- modal-body end -->

    </div>
  </div>
</div>