config/routes.rb
Rails.application.routes.draw do

  get 'reviews/index'

  root 'pages#index'
  get 'pages/index'

  devise_for :users, 
  	path: '', 
  	path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile'},
  	controllers: {:omniauth_callbacks => 'omniauth_callbacks', :registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:show]

  resources :rooms do
    resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end
  
	resources :photos
  resources :contacts, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/trips' => 'reservations#trips'
  get '/my_reservations' => 'reservations#my_reservations'
	
  post "/trips" => "reservations#trips"
  post "/notify" => "reservations#notify"

  get '/search' => "pages#search"
end

app/models/room.rb
class Room < ApplicationRecord
  searchkick word_start: [:listing_name, :kor_address], 
             word_middle: [:listing_name, :kor_address]
  
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # 필터링할 욕의 종류
  words = ["shit", "fuck", "hell"]
  
  # 저장전에 실행
  before_save{ 
    words.each do |word| 
      len = word.length
      self.summary.gsub!(/#{word}/, '*'*len) if(self.summary.include?(word))
    end
  }


  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 50}
  validates :summary, presence: true, length: {maximum: 500}
  validates :address, presence: true
  validates :price, presence: true

  def average_rating(key)
    reviews.count == 0 ? 0 : reviews.average(key).to_i.round(1)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = Room.all
    @myrooms = current_user.rooms
  end

  def show
    @photos = @room.photos
    @booked = Reservation.where( "room_id = ? AND user_id = ?", 
      @room.id, current_user.id ).present? if current_user

    @reviews = @room.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    
    if @room.save
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image:image)
        end
      end

      @photos = @room.photos
      redirect_to @room, notice: "성공적으로 숙소를 등록했어요!"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, alert: "수정권한이 없습니다!"  
    end
    
  end

  def update
    if @room.update(room_params)

      if @room.save
        if params[:images]
          params[:images].each do |image|
            @room.photos.create(image:image)
          end
        end
      end
      
      redirect_to @room, notice: "성공적으로 숙소 정보를 수정했어요!"
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def set_room
    @room = Room.find(params[:id])  
  end

  def room_params
    params.require(:room).permit(
      :home_type,
      :room_type,
      :accommodate,
      :bed_room,
      :bath_room,
      :listing_name,
      :summary,
      :address,
      :kor_address,
      :is_tv,
      :is_kitchen,
      :is_air,
      :is_heating,
      :is_wifi,
      :price,
      :active,
      :check_in,
      :check_out
    )
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div id="new-room" class="container margin-top">
	<%=form_for(@room, html: {multipart: true}) do |f|%>
		<div class="row">
			<div class="col-md-8">
				<h3>등록하실 숙소 종류는 무엇인가요?</h3>

				<label for="room_home_type">숙소의 건물유형을 알려주세요.</label>
				<%= f.text_field :home_type, list: 'home-type', placeholder:"건물유형", class: "form-control"%>
				<datalist id="home-type">
				  <option value="단독주택">
				  <option value="아파트">
				  <option value="게스트하우스">
				</datalist>
				<br>
				<label for="room_room_type">게스트가 묵을 방 유형</label>
				<%= f.text_field :room_type, list: 'room-type', placeholder:"방 유형" , class: "form-control"%>
				<datalist id="room-type">
				  <option value="집 전체">
				  <option value="개인실">
				  <option value="다인실">
				</datalist>
			</div>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="fa fa-lightbulb-o" aria-hidden="true"></i>	
					</div>
					<div class="panel-body">
						<strong>집 전체</strong> : 게스트에게 별채를 포함한 집 전체를 빌려줍니다. <br>
						<strong>개인실</strong> : 호스트와 공유하는 공간이 있긴 하지만 게스트에게 잠을 잘 수 있는 개인실이 제공됩니다. <br>
						<strong>다인실</strong> : 게스트가 단독으로 쓸 수 있는 방이 제공되지 않습니다. <br>
					</div>
				</div>
			</div>
		</div>
		
		<hr>

		<div class="row">
			<div class="col-md-8">
			<h3>숙소에 얼마나 많은 인원이 숙박할 수 있나요?</h3>

				<label for="room_accommodate">숙박인원</label><br>
				<%=f.select :accommodate, [["1",1],["2",2],["3",3],["4",4],["5",5],["6+",6]], prompt: "숙박인원"%>
				<br><br>

				<label for="room_bed_room">게스트가 몇 개의 침실을 사용할 수 있나요?</label><br>
				<%=f.select :bed_room, [["1",1],["2",2],["3",3],["4",4],["5",5],["6+",6]], prompt: "침실" %>
				<br><br>

				<label for="room_bath_room">욕실은 몇 개인가요? </label><br>
				<%=f.select :bath_room, [["1",1],["2",2],["3",3],["4",4],["5",5],["6+",6]], prompt: "욕실" %>
			</div>

			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="fa fa-lightbulb-o" aria-hidden="true"></i>	
					</div>
					<div class="panel-body">
						회원님 숙소의 침대 수와 종류에 따라 몇 명의 인원이 불편함 없이 머물 수 있는지가 결정됩니다. <br>
						침대 유형을 명시하면 게스트가 어떤 종류의 침대가 있는지 알 수 있습니다.
					</div>
				</div>
			</div>			
		</div>
		
		<hr>


		<div class="row">
			<div class="col-md-8">
				<h3>정보를 제공해 주세요.</h3>
				<p>사진, 간단한 설명, 제목등</p>

				<label for="room_listing_name">숙소 이름지정</label>
				<%=f.text_field :listing_name, placeholder: "숙소이름" , class: "form-control"%><br>

				<label for="room_summary">숙소 설명을 작성하세요</label>
				<%=f.text_area :summary, rows:5, placeholder: "숙소의 장점, 가까운 명소, 멋진경치, 채광, 편안한 침대 등" , class: "form-control"%><br>

				<label for="room_address">숙소 위치</label>
				<!-- onchange 이벤트시 initMap()을 실행한다. -->
				<%=f.text_field :address, placeholder: "영문주소(필수)", class: "form-control", onchange: "initMap()"%><br>

				<%=f.text_field :kor_address, placeholder: "한글주소(영문 주소값이 있으면 자동으로 생성됩니다.)", class: "form-control"%><br>
				<!-- 영문주소를 자동으로 한글주소로 바꿔 :kor_address에 기입해주는 메서드 순수 js로 작성하는 버릇을 갖자-->
				<script>
					function initMap() {
					  var address = document.getElementById('room_address').value;
						var geocoder = new google.maps.Geocoder();
	  				geocodeAddress(geocoder,address);	
					}

  				function geocodeAddress(geocoder,address){
  					geocoder.geocode({'address': address}, function(results, status){
  						geocoder.geocode({'location': results[0].geometry.location}, function(results, status){
  							console.log(results[0].formatted_address);
  							var kor_address = document.getElementById('room_kor_address');
  							kor_address.value = results[0].formatted_address;
  						})
  					});
  				}
				</script>

				<label>숙소 사진</label><br>
				<span class="btn btn-default btn-file">
					<i class="fa fa-cloud-upload fa-lg"></i> 사진올리기
					<%=file_field_tag "images[]", type: :file, multiple: true%>
				</span>
				

				<br>

				<div id="photos">
					<h5>사진 미리보기</h5>
					<div id="preview" class="row text-center">
						미리보기 할 사진이 없습니다.
					</div>
					<%= render 'photos/list'%>
				</div>

			</div>
			
			

			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="fa fa-lightbulb-o" aria-hidden="true"></i>	
					</div>
					<div class="panel-body">
						여기에 작성한 설명이 숙소 페이지 맨 위에 표시됩니다. 게스트가 숙소를 검색할 때 일반적으로 궁금해 하는 질문 몇 가지를 제시해 보았습니다. 내용은 나중에 수정하거나 추가하실 수 있습니다. <br>
						또한, 개인적 배경과 관계없이 모든 게스트를 환영한다는 메시지를 숙소 설명에 포함할 수 있습니다.
					</div>
				</div>
			</div>

		</div>
		
		<hr>

		<div class="row">
			<div class="col-md-8">
			<h3>어떤 편의시설을 제공하시나요?</h3>
				<label for="room_is_tv">TV</label>
					<%=f.check_box :is_tv%><br>
				<label for="room_is_kitchen">부엌</label>
					<%=f.check_box :is_kitchen%><br>
				<label for="room_is_air">에어컨</label>
					<%=f.check_box :is_air%><br>
				<label for="room_is_heating">히터</label>
					<%=f.check_box :is_heating%><br>
				<label for="room_is_wifi">무선인터넷</label>
					<%=f.check_box :is_wifi%><br>
			</div>

			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="fa fa-lightbulb-o" aria-hidden="true"></i>	
					</div>
					<div class="panel-body">
						일부 호스트는 조식 또는 커피와 차만 제공하기도 합니다. 필수 사항은 아니지만, 이런 서비스를 제공하면 게스트가 보다 환영받는다고 느낄 수 있습니다.
					</div>
				</div>
			</div>
		</div>
		
		<hr>

		<div class="row">
			<div class="col-md-8">
				<h3>기본요금</h3>
				<p>기본 요금은 회원님이 정한 기본 1박당 요금입니다.</p>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-addon">KRW(원)</div>
						<%=f.text_field :price, placeholder: "50,000", class: "form-control"%> 
					</div>
				</div>
					
			</div>

			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<i class="fa fa-lightbulb-o" aria-hidden="true"></i>	
					</div>
					<div class="panel-body">
						기본 1박당 요금 처음에는 요금을 낮게 책정했다가 긍정적인 리뷰를 받은 다음에 요금을 올리는 호스트들도 있습니다.수요에 따라 가격을 변경할 수 있습니다. <br>
						예를 들어, 성수기에 가격을 높게 책정하면 더 많은 수익을 얻을 수 있고, 비수기에 가격을 낮게 책정하면 더 많은 예약을 받을 수 있습니다.
					</div>
				</div>
			</div>
		</div>
		
		<hr>
		<div class="row">
		<h3>체크인/아웃 가능 시간을 선택해 주세요.</h3>

			<div class="col-md-6">
				<label for="room_check_in">체크인</label><br>
			  <%= f.time_field :check_in, 
			  	value: "%H:%M", 
			  	min: 'hh:mm:ss', 
			  	max: 'hh:mm:ss'
			  %>
			</div>

			<div class="col-md-6">
			  <label for="room_check_out">체크아웃</label><br>
			  <%= f.time_field :check_out, 
			  	value: "%H:%M", 
			  	min: 'hh:mm:ss', 
			  	max: 'hh:mm:ss'
			  %>
		  </div>
		</div>

		<hr>

		<div class="row">
			<h3>예약 가능 여부 설정</h3>
			<%=f.check_box :active%>
		</div>
		<hr>
		<%=f.submit "완료", class: "btn btn-lg btn-green"%>
	<%end%>
</div>

app/views/rooms/edit.html.erb
<div class="container">
	<h1>숙소정보를 수정하고 게스트를 맞이하세요.</h1>
	<%=render 'form'%>
</div>

app/views/rooms/index.html.erb
<div class="container margin-top">
	<div class="row">
		<div class="col-md-3">
			<ul>
				<li class="h4 active"><%=link_to("숙소 목록", rooms_path)%></li>
				<li class="h4"><%=link_to("예약 관리", my_reservations_path)%></li>
				<%=link_to "새로운 숙소 추가", new_room_path, class: 'btn btn-green'%>
			</ul>
			<br>
		</div>
		<div class="col-md-9">
			<div class="panel panel-default">
				<div class="panel-heading">
					운영중인 숙소
				</div>
				<div class="panel-body">
				<%if @myrooms.length > 0%>
					<% @myrooms.each do |room|%>
						<div class="row room_list">
							<div class="col-md-5">
								<% if room.photos.length > 0%>
									<%=link_to room do %>
										<%= image_tag(room.photos[0].image.url(), class: "img-responsive") if room.photos.length > 0 %>
									<%end%>
								<%else%>
									<%=image_tag("missing", class: "img-responsive")%>
								<%end%>
							</div>
							<div class="col-md-7">
								<h4><%=link_to room.listing_name, room, class: "h4"%></h4>
								<p>최종 업데이트: <%=room.updated_at.strftime("%Y년 %m월 %d일")%></p>
								<%=link_to "정보 수정", edit_room_path(room), class: 'btn btn-green'%>
							</div>
						</div>
						<hr>
					<%end%>
				<%else%>
					<p>예정된 숙소가 없습니다.</p>
					<h3>에어비앤비 호스트가 되어 회원님의 꿈을 실현하세요!</h3>
					<%=link_to "호스팅하기", new_room_path, class: 'btn btn-lg btn-green'%>
				<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/new.html.erb
<div class="container margin-top">
<h1>게스트를 맞이할 준비를 하세요.</h1>

<%=render 'form'%>
</div>

app/views/rooms/show.html.erb
<div class="cover-image-container">
	<% if @room.photos.length > 0%>
		<div class="cover-img" style="background-image: url(<%=@room.photos[0].image.url()%>);">
			<a class="btn btn-default" data-toggle="modal" data-target="#imgModal" style="cursor: pointer;">사진보기</a>
		</div>
	<%else%>
		<div class="cover-img cover-img-placeholder"></div>
	<%end%>
</div>
<!-- modal -->

<%=render 'share/room-img-slider-modal'%>

<!-- summary -->
<div class="container summary">
	<div class="row">
		<div class="col-md-8">
			<div class="row">
				<div class="col-md-3 text-center">
					<br>
					<%=link_to(@room.user)do%>
						<%=image_tag avatar_url(@room.user), class: "img-circle avatar-large"%>
						<h5><%= @room.user.username%></h5>
					<%end%>
				</div>

				<div class="col-md-9">
					<div class="summary-room-info">
						<h3><%=@room.listing_name%></h3>
						<p id="address"><%=@room.kor_address%></p>
					</div>
					<div class="row text-center">
						<div class="col-xs-3">
							<i class="fa fa-home fa-2x" aria-hidden="true"></i>
							<p class="h5"><%=@room.room_type%></p>
						</div>
						<div class="col-xs-3">
							<i class="fa fa-user fa-2x" aria-hidden="true"></i>
							<p class="h5">인원 <%=@room.accommodate%>명</p>
						</div>
						<div class="col-xs-3">
							<i class="fa fa-bath fa-2x" aria-hidden="true"></i>
							<p class="h5">욕실 <%=@room.bath_room%>개</p>
						</div>
						<div class="col-xs-3">
							<i class="fa fa-bed fa-2x" aria-hidden="true"></i>
							<p class="h5">침실 <%=@room.bed_room%>개</p>
						</div>

					</div>
				</div>

			</div>
		</div>

		<div class="col-md-4">
			<%=render 'reservations/form'%>
		</div>
	</div>
</div>

<hr>

<div class="container details">
	<div class="row">
		<div class="col-md-12">
			<h4>상세설명</h4>
			<p></p>	
		</div>
		<hr class="col-md-8">	
	</div>

	<div class="row">
		<div class="col-md-2">숙소</div>
		<div class="col-md-3">
			<ul>
				<li>숙박 가능 인원: <span class="h5"><%=@room.accommodate%></span></li>
				<li>욕실: <span class="h5"><%=@room.bath_room%></span></li>
				<li>침실: <span class="h5">	<%=@room.bed_room%></span></li>
				<li>집 유형: <span class="h5"><%=@room.home_type%></span></li>
			</ul>
		</div>
		<div class="col-md-3">
			<ul>
				<li>숙소 유형: <span class="h5"><%=@room.room_type%></span></li>
				<li>체크인: <span class="h5"><%=@room.check_in.strftime("%p %I시 %M분 ")%></span></li>
				<li>체크아웃: <span class="h5"><%=@room.check_out.strftime("%p %I시 %M분 ")%></span></li>
			</ul>
		</div>
		<hr class="col-md-8">
	</div>

	<div class="row">
		<div class="col-md-2">시설</div>
		<div class="col-md-3">
			<ul>
				<%=@room.is_tv ? raw("<li class=\"h5\"><i class=\"fa fa-tv\" aria-hidden=\"true\"></i> TV</li>") : raw("<li><del>TV</del><li>")%>
				<%=@room.is_kitchen ? raw("<li class=\"h5\"><li class=\"h5\"><i class=\"fa fa-cutlery\" aria-hidden=\"true\"></i> 부엌</li>") : raw("<li><del>부엌</del><li>")%>
				<%=@room.is_air ? raw("<li class=\"h5\"><li class=\"h5\"><i class=\"fa fa-snowflake-o\" aria-hidden=\"true\"></i> 에어컨</li>") : raw("<li><del>에어컨</del><li>")%>
			</ul>
		</div>
		<div class="col-md-3">
			<ul>
				<%=@room.is_heating ? raw("<li class=\"h5\"><li class=\"h5\"><i class=\"fa fa-thermometer-2\" aria-hidden=\"true\"></i> 히터</li>") : raw("<li><del>히터</del><li>")%>
				<%=@room.is_wifi ? raw("<li class=\"h5\"><li class=\"h5\"><i class=\"fa fa-wifi\" aria-hidden=\"true\"></i> 무선 인터넷</li>") : raw("<li><del>무선 인터넷</del><li>")%>
			</ul>
		</div>
		<hr class="col-md-8">
	</div>

	<div class="row">
		<div class="col-md-2">설명</div>
		<div class="col-md-6"><%=@room.summary%></div>
		<hr class="col-md-8">
	</div>

	<div class="row">
		<div class="col-md-2">숙소 이용규칙</div>
		<div class="col-md-6">체크인은 <%=@room.check_in.strftime("%H시 :%M ")%> 이후입니다.</div>
	</div>
	
</div>

<hr>

<!-- reviews -->
<div class="container review">
	<%=render "reviews/list"%>
	<%=render "reviews/form" if @booked && !@hasReview%>
</div>

<hr>
<!-- map -->
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h4>숙소설명</h4>
			<p>에어비앤비를 이용하면 누군가의 소중한 집에 머무르는 것입니다.</p>
		</div>
		<hr class="col-md-8">
		<div class="col-md-12">
			<div id="map" style="width: 100%; height: 648px;"></div>
		</div>
	</div>
</div>

<!-- nearby -->

<div id="nearby_rooms" class="container">
	<div class="row">
		<div class="col-md-12">
			<br>
			<h4>근처 또 다른 숙소</h4>
			<br>
		</div>

		<%for room in @room.nearbys(10, units: :km)%>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading preview">
						
						<% if room.photos.length > 0%>
							<%=image_tag room.photos[0].image.url(:medium)%>
						<%else%>
							<%=image_tag("room_default_no_photos")%>
						<%end%>

					</div>
					<div class="panel-body">
						<h4><%=link_to room.listing_name, room%></h4>
						<%=room.room_type%> - 거리: <%=room.distance.round(2)%> 킬로미터
					</div>
				</div>
			</div>
		<%end%>
	</div>
</div>


<hr>

<script>

$(document).ready(function() {
	var $sticker = $('#sticker'),
			$window = $(window);

  $window.resize(function() {

    if(false == $sticker.hasClass('sticker') && $window.width() >= 990) {
      $sticker.addClass('sticker');
      $(".sticker").sticky({topSpacing:0});
    }

    if(true == $sticker.hasClass('sticker') && $window.width() < 990) {
      $sticker.removeClass('sticker');
    }
  });

});
</script>